### ISSUE TITLE
0.2.11 is a breaking change

### ISSUE THREAD

**Issue by zeylahellyer** [simd-lite/value-trait#22]
Updating the minimum supported rust version is a breaking change and has resulted in us needing to restrict our dependency to an old version. Although not explicitly disallowed by Cargo's [standard semver policy](https://doc.rust-lang.org/cargo/reference/semver.html), it would be nice to document whether you intend to follow semver in this regard.

**Comment by Licenser** [comment]
Heya,

sorry about that. in short, yes so semver with a 0.x is a bit of the wild west, the change here, stabilizing arm support was one of the major blockers for a full 1.0 release so with this merged 1.0.0 should be on the horizon :)

**Comment by zeylahellyer** [comment]
Thanks for the explanation, it's good to hear it's in the goal of that.
