### ISSUE TITLE
fails to build on ppc64le

### ISSUE THREAD

**Issue by nekopsykose** [simd-lite/value-trait#41]
```
error: write_str_simd not supported on the current architecture
   --> /home/buildozer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/value-trait-0.6.1/src/generator.rs:370:9
    |
370 |         compile_error!("write_str_simd not supported on the current architecture")
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

of course, this comes from
```rs
    #[cfg(all(
        not(target_arch = "aarch64"),
        not(all(target_arch = "wasm32", target_feature = "simd128")),
        not(any(target_feature = "avx2", target_feature = "sse2")),
        feature = "allow-non-simd"
    ))]
    #[inline(always)]
    /// Writes a string with simd-acceleration (not really, as the architecture doesn't support it)
    /// # Safety
    /// This function is unsafe because it uses simd instructions
    /// # Errors
    ///  if the write fails
    unsafe fn write_str_simd(&mut self, string: &mut &[u8]) -> io::Result<()> {
        self.write_simple_string(std::str::from_utf8_unchecked(string))
    }

    #[cfg(all(
        not(target_arch = "aarch64"),
        not(all(target_arch = "wasm32", target_feature = "simd128")),
        not(any(target_feature = "avx2", target_feature = "sse2")),
        not(feature = "allow-non-simd")
    ))]
    unsafe fn write_str_simd(&mut self, string: &mut &[u8]) -> io::Result<()> {
        compile_error!("write_str_simd not supported on the current architecture")
    }
```

is there a reason to have a fallback to nothing (no simd) on aarch64, but compile error on others? afaict it should be the aarch64 case as a fallback for every architecture, but maybe i'm missing something

**Comment by hustcer** [comment]
I got the same error while building `armv7` and `riscv64` version of Nushell packages, detailed error could be found here: https://github.com/nushell/nushell/actions/runs/5239108268/jobs/9458637974, Is there a work around? Thanks

**Comment by Licenser** [comment]
Ja it should always fall back, this is addresse din #42 :)

**Comment by nekopsykose** [comment]
thanks! :)

**Comment by hustcer** [comment]
@Licenser https://github.com/simd-lite/simd-json/blob/8bb52e4b08928bb8474f7d0066791139236a5180/Cargo.toml#L23
`simd-json` still depends on an old version of `value-trait`, maybe a new version of `simd-json`  with the latest `value-trait` should be released?

**Comment by Licenser** [comment]
there is a [**very big** update](https://github.com/simd-lite/value-trait/pull/43) incoming for value-trait (and following there simd-json and simd-json-derive) I wanted to combine those before releasing a new simd-json version.

The code is done, just giving it a day to collect feedback on the PR and it should be released tomorrow :)

**Comment by Licenser** [comment]
This is released as `v0.13.0`

**Comment by mgiessing** [comment]
@Licenser 
I'm trying to build on ppc64le, but I still get an error (on x86 and emulated aarch64 it works just fine)

```bash
[...]
   Compiling value-trait v0.8.0 (/value-trait)
     Running `/root/.rustup/toolchains/stable-powerpc64le-unknown-linux-gnu/bin/rustc --crate-name value_trait --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=230 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="custom-types"' --cfg 'feature="default"' --cfg 'feature="halfbrown"' --cfg 'feature="runtime-detection"' -C metadata=44a780307e594cda -C extra-filename=-44a780307e594cda --out-dir /value-trait/target/debug/deps -C incremental=/value-trait/target/debug/incremental -L dependency=/value-trait/target/debug/deps --extern float_cmp=/value-trait/target/debug/deps/libfloat_cmp-33b493179a3e62b9.rmeta --extern halfbrown=/value-trait/target/debug/deps/libhalfbrown-755caa2224a35cf5.rmeta --extern itoa=/value-trait/target/debug/deps/libitoa-26c23715b9f2e8d9.rmeta --extern ryu=/value-trait/target/debug/deps/libryu-02b6ce7ec4833be8.rmeta`
error[E0599]: no method named `write_str_simd` found for mutable reference `&mut Self` in the current scope
   --> src/generator.rs:137:24
    |
137 |             stry!(self.write_str_simd(&mut string));
    |                        ^^^^^^^^^^^^^^ help: there is a method with a similar name: `write_string`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `value-trait` (lib) due to previous error

Caused by:
  process didn't exit successfully: `/root/.rustup/toolchains/stable-powerpc64le-unknown-linux-gnu/bin/rustc --crate-name value_trait --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=230 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="custom-types"' --cfg 'feature="default"' --cfg 'feature="halfbrown"' --cfg 'feature="runtime-detection"' -C metadata=44a780307e594cda -C extra-filename=-44a780307e594cda --out-dir /value-trait/target/debug/deps -C incremental=/value-trait/target/debug/incremental -L dependency=/value-trait/target/debug/deps --extern float_cmp=/value-trait/target/debug/deps/libfloat_cmp-33b493179a3e62b9.rmeta --extern halfbrown=/value-trait/target/debug/deps/libhalfbrown-755caa2224a35cf5.rmeta --extern itoa=/value-trait/target/debug/deps/libitoa-26c23715b9f2e8d9.rmeta --extern ryu=/value-trait/target/debug/deps/libryu-02b6ce7ec4833be8.rmeta` (exit status: 1)
[...]
```

Not sure I'm doing anything wrong, but this is a minimal reproducible example

```bash
podman run -ti --rm quay.io/pypa/manylinux2014_ppc64le

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source $HOME/.cargo/env

git clone -b v0.8.0 https://github.com/simd-lite/value-trait && cd value-trait

cargo build --verbose
```

In theory Power supports SIMD via Altivec/VSX but even without the intrinsic code it should use a non-SIMD fallback solution, shouldn't it?

Thanks!

**Comment by Licenser** [comment]
Sorry for the late reply, I'm on vacation right now and only occasionally look at the computer.

you have to disable the runtime-detection feature for the fallback, I'm not sure that's the best solution but it really becomes tricky with the mix of different architectures and their supports. This might change in the future and be easier to deal with but for now that's the quickest way :)

**Comment by mgiessing** [comment]
Your reply was more than fast, especially if you're on vacation - all good :) 
Disabling runtime-detection works fine, however I'm not sure I fully understand why the condition (is runtime-detection enabled?) is in the fallback part.

My (naive/simple) assumption would be like:

- is_x86_feature_detected?
  - target_feature=AVX2? => use AVX2 SIMD
  - target_feature=SSE? => use SSE SIMD
- is_aarch64_feature_detected? => use NEON SIMD
- everything else => scalar

At least that's usually the way I see it in C/C++ projects:

```c
#if defined(__AVX2__) 
  //AVX2 SIMD
#elif defined(__ARM_NEON)
  //ARM NEON SIMD
  #if defined(__ARM_FEATURE_DOTPROD)
    // Special ARM DOTPROD SIMD
  #else
    // ARM SIMD
  #endif
#elif defined(__VSX__)
  //ppc64le VSX SIMD
#else
  //scalar for all other platforms
#endif
```

Potentially the "sub conditions" could be enhaced, e.g. for x86 by checking for SSE41, SSE42, AVX512 etc.
Then everybody who is interested adding SIMD for a specific platform like ppc64le/riscv64/s390x etc. could just add another condition.

Thanks a lot, enjoy your vacation and merry christmas!

**Comment by Licenser** [comment]
the c++ snipped you post isn't runtime detection, that's compiletime detection. Runtimedetection has advantages on x86 since there are a gazillion instruction sets that offer different advantages on other platforms it's more a binary choice (or at least a lot less common and probably not worth the cost, I think)

Downside is that runtime detection is computationally expensive, every invocation of the function it adds overhead. That's not the greatest :tm: thing on the planet, especially in the value-trait I didn't manged to put this into a function pointer (yay lifetimes :sob:)

So it boils down to one of:

1. Pay the cost for runtime detection on every platform all the time
2. make the `runtime-detection` flag a no-op on non x86 platforms and possibly confuse people
3. make it not work on x86 platforms and have people disable it if they compile for non x86 platforms
4. leave to off by default but deal with the downside of 3. if anyone enables it anyway

I opted for 3. for two reasons. I prefer loud errors over silent degrading ones - I rather have people turn off runtime detection and know about it, then see the flag, put it in, have it have no effect and then 1 year into prudciton notice it has no effect. x86 is still the most common platform, so for a majority of users it will make sense (that's a guess I've no data to support it aside of personal experience).
