### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by drauschenbach** [simd-lite/value-trait#47]
https://github.com/simd-lite/value-trait/pull/46 was not just a patch release, it contained fundamental fixes to build pipelines of dependent projects, in particular `simd-json` used by `polars-json`.

armv7 support for this broad range projects won't be fixed until value-trait is re-released as a Semver "minor" (not patch) version increment.

**Comment by Licenser** [comment]
Hi, can you explain why this is needed? I'm not quite sure I'm following the problem.

**Comment by drauschenbach** [comment]
I'm looking for a way for `simd-json` to pick up this change, which it hasn't for months. `simd-json` requires `0.8`. When cargo builds my project it is ignoring your last very important fix, I think because you categorized it as a patch release rather than a minor (0.9) or major (1.0) release.

**Comment by Licenser** [comment]
Have you tried running `cargo update` that should fetch the newest versions. simd-json defines `0.8` as dependency wich means "the highest patch of the 0.8 version". But if your lock file has locked in a older version of value-trait already then you'll need to run `cargo update` or delete the `Cargo.lock` file to re-generate it.

**Comment by drauschenbach** [comment]
Thanks! My old workflow was `cargo outdated -R`, which is where transitive dependencies were getting skipped.

**Comment by Licenser** [comment]
glad we solved it the easy way :D
